// afh-data.jsx — Mock data v3 (Code Mode + Creative Mode)

export const PROJECTS = [
  {
    id: 'commerce-api',
    name: 'commerce-api',
    mode: 'code',
    stack: ['Node.js', 'Express', 'PostgreSQL', 'Redis'],
    testCmd: 'npm test',
    activeRole: 'Backend Engineer',
    runsToday: 4,
    successRate: 82,
  },
  {
    id: 'auth-service',
    name: 'auth-service',
    mode: 'code',
    stack: ['Go', 'PostgreSQL', 'Redis'],
    testCmd: 'go test ./...',
    activeRole: 'Security Engineer',
    runsToday: 3,
    successRate: 58,
  },
  {
    id: 'brand-video-q2',
    name: 'brand-video-q2',
    mode: 'creative',
    stack: ['Gemini', 'Runway', 'Claude'],
    testCmd: null,
    activeRole: 'Creative Director',
    runsToday: 2,
    successRate: 70,
  },
  {
    id: 'ml-pipeline',
    name: 'ml-pipeline',
    mode: 'code',
    stack: ['Python', 'FastAPI', 'PostgreSQL'],
    testCmd: 'pytest -v',
    activeRole: 'Data Engineer',
    runsToday: 2,
    successRate: 94,
  },
  {
    id: 'product-demo-video',
    name: 'product-demo-video',
    mode: 'creative',
    stack: ['Gemini', 'Midjourney', 'Kling'],
    testCmd: null,
    activeRole: 'Creative Director',
    runsToday: 1,
    successRate: 50,
  },
];

export const RUNS = [
  {
    id: 'run-5001',
    project: 'brand-video-q2',
    mode: 'creative',
    role: 'Creative Director',
    task: 'Brand Launch Video — Q2 2026',
    status: 'waiting_review',
    startedAt: '2026-04-24T14:10:00Z',
    duration: '18m 32s',
    tokensUsed: 28400,
    estimatedCost: 4.20,
    stepsDone: 3,
    stepsTotal: 6,
    assetsGenerated: 8,
    assetsPendingReview: 3,
  },
  {
    id: 'run-4821',
    project: 'commerce-api',
    mode: 'code',
    role: 'Backend Engineer',
    task: 'Implement cart abandonment webhook handler',
    status: 'running',
    startedAt: '2026-04-24T14:32:00Z',
    duration: '8m 14s',
    tokensUsed: 42800,
    estimatedCost: 0.21,
    fixAttempts: 1,
    maxFix: 5,
    stepsDone: 4,
    stepsTotal: 8,
    testPass: 7,
    testFail: 3,
  },
  {
    id: 'run-4820',
    project: 'auth-service',
    mode: 'code',
    role: 'Security Engineer',
    task: 'Refactor OAuth token refresh flow',
    status: 'escalated',
    startedAt: '2026-04-24T13:10:00Z',
    duration: '22m 44s',
    tokensUsed: 98400,
    estimatedCost: 0.49,
    fixAttempts: 5,
    maxFix: 5,
    stepsDone: 6,
    stepsTotal: 8,
    testPass: 11,
    testFail: 2,
  },
  {
    id: 'run-5000',
    project: 'product-demo-video',
    mode: 'creative',
    role: 'Creative Director',
    task: 'Product Demo — Hero Section Video',
    status: 'success',
    startedAt: '2026-04-24T11:00:00Z',
    duration: '42m 10s',
    tokensUsed: 18200,
    estimatedCost: 6.80,
    stepsDone: 6,
    stepsTotal: 6,
    assetsGenerated: 12,
    assetsPendingReview: 0,
  },
  {
    id: 'run-4819',
    project: 'commerce-api',
    mode: 'code',
    role: 'Backend Engineer',
    task: 'Add pagination to product search endpoint',
    status: 'success',
    startedAt: '2026-04-24T12:05:00Z',
    duration: '6m 32s',
    tokensUsed: 31200,
    estimatedCost: 0.16,
    fixAttempts: 1,
    maxFix: 5,
    stepsDone: 8,
    stepsTotal: 8,
    testPass: 14,
    testFail: 0,
  },
  {
    id: 'run-4818',
    project: 'ml-pipeline',
    mode: 'code',
    role: 'Data Engineer',
    task: 'Migrate feature store to async batch processing',
    status: 'success',
    startedAt: '2026-04-24T11:20:00Z',
    duration: '14m 08s',
    tokensUsed: 67100,
    estimatedCost: 0.34,
    fixAttempts: 2,
    maxFix: 5,
    stepsDone: 8,
    stepsTotal: 8,
    testPass: 22,
    testFail: 0,
  },
  {
    id: 'run-4817',
    project: 'auth-service',
    mode: 'code',
    role: 'Security Engineer',
    task: 'Add rate limiting middleware',
    status: 'failed',
    startedAt: '2026-04-24T10:00:00Z',
    duration: '18m 55s',
    tokensUsed: 89200,
    estimatedCost: 0.45,
    fixAttempts: 5,
    maxFix: 5,
    stepsDone: 5,
    stepsTotal: 8,
    testPass: 8,
    testFail: 4,
  },
  {
    id: 'run-4999',
    project: 'brand-video-q2',
    mode: 'creative',
    role: 'Creative Director',
    task: 'Brand Launch Video — Teaser Cut',
    status: 'failed',
    startedAt: '2026-04-23T16:00:00Z',
    duration: '55m 22s',
    tokensUsed: 22100,
    estimatedCost: 8.10,
    stepsDone: 4,
    stepsTotal: 6,
    assetsGenerated: 6,
    assetsPendingReview: 0,
  },
  {
    id: 'run-4816',
    project: 'ml-pipeline',
    mode: 'code',
    role: 'Data Engineer',
    task: 'Add model versioning to training pipeline',
    status: 'success',
    startedAt: '2026-04-23T21:00:00Z',
    duration: '16m 02s',
    tokensUsed: 74600,
    estimatedCost: 0.37,
    fixAttempts: 1,
    maxFix: 5,
    stepsDone: 8,
    stepsTotal: 8,
    testPass: 26,
    testFail: 0,
  },
];

// Code Mode Run Detail Steps
export const CODE_RUN_STEPS = [
  {
    id: 's1', name: 'Collect Context', status: 'success',
    duration: '1.2s', tokens: 4200, startedAt: '14:32:00',
    input: 'Task: Implement cart abandonment webhook handler\nProject: commerce-api\nStack: Node.js, Express, PostgreSQL',
    output: 'Collected 6 context sources\nTotal context: 4,200 tokens',
    collectorBreakdown: [
      { name: 'schema.sql', tokens: 1240, pct: 29 },
      { name: 'routes/cart.js', tokens: 880, pct: 21 },
      { name: 'models/Order.js', tokens: 640, pct: 15 },
      { name: 'docs/webhooks.md', tokens: 720, pct: 17 },
      { name: 'tests/cart.test.js', tokens: 520, pct: 12 },
      { name: 'package.json', tokens: 200, pct: 5 },
    ],
  },
  {
    id: 's2', name: 'Plan Implementation', status: 'success',
    duration: '3.8s', tokens: 6800, startedAt: '14:32:01',
    input: 'Context: 4,200 tokens\nTask: Implement cart abandonment webhook',
    output: '1. Add POST /webhooks/cart-abandoned route\n2. Validate Shopify HMAC signature\n3. Parse payload and upsert abandoned_carts table\n4. Trigger email notification job\n5. Return 200 with idempotency',
  },
  {
    id: 's3', name: 'Generate Code', status: 'success',
    duration: '8.4s', tokens: 14200, startedAt: '14:32:05',
    input: 'Plan: 5 implementation steps\nFiles: routes/webhooks.js, models/AbandonedCart.js',
    output: 'Generated 3 files (304 lines total)\nModified: routes/index.js',
    diff: {
      before: `// routes/index.js
const cartRoutes = require('./cart');
const orderRoutes = require('./orders');

router.use('/cart', cartRoutes);
router.use('/orders', orderRoutes);`,
      after: `// routes/index.js
const cartRoutes = require('./cart');
const orderRoutes = require('./orders');
const webhookRoutes = require('./webhooks');

router.use('/cart', cartRoutes);
router.use('/orders', orderRoutes);
router.use('/webhooks', webhookRoutes);`,
    },
  },
  {
    id: 's4', name: 'Run Tests', status: 'failed',
    duration: '12.1s', tokens: 8400, startedAt: '14:32:14',
    input: 'Command: npm test -- --testPathPattern=webhook',
    output: 'FAIL tests/webhooks.test.js\n✓ validates HMAC (245ms)\n✓ returns 401 on invalid sig (180ms)\n✗ upserts cart record (TimeoutError)\n✗ triggers email job (TypeError)\n✗ idempotent for duplicates (AssertionError)\n\nTests: 2 passed, 3 failed',
    testResults: [
      { name: 'validates HMAC signature', status: 'pass', duration: '245ms' },
      { name: 'returns 401 on invalid signature', status: 'pass', duration: '180ms' },
      { name: 'upserts abandoned cart record', status: 'fail', errorType: 'TimeoutError', error: 'Timeout of 5000ms exceeded.\n  at AbandonedCart.upsert (models/AbandonedCart.js:34)\n  Expected: record inserted within 5s\n  Received: Promise pending after 5002ms', file: 'tests/webhooks.test.js', line: 67 },
      { name: 'triggers email job on new cart', status: 'fail', errorType: 'TypeError', error: "TypeError: emailNotification.enqueue is not a function\n  at routes/webhooks.js:52:28\n  Expected: job enqueued\n  Received: TypeError thrown", file: 'tests/webhooks.test.js', line: 89 },
      { name: 'is idempotent for duplicate payloads', status: 'fail', errorType: 'AssertionError', error: "AssertionError: expected 2 to equal 1\n  Expected: 1 record (upsert dedup)\n  Received: 2 records inserted", file: 'tests/webhooks.test.js', line: 112 },
    ],
  },
  {
    id: 's5', name: 'Fix Attempt 1 / 5', status: 'running',
    duration: null, tokens: 9200, startedAt: '14:32:26',
    input: 'Failures: TimeoutError in AbandonedCart.upsert, TypeError emailNotification.enqueue, AssertionError idempotency',
    output: null,
  },
  { id: 's6', name: 'Fix Attempt 2 / 5', status: 'pending', duration: null, tokens: null, startedAt: null, input: null, output: null },
  { id: 's7', name: 'Run Tests (Final)', status: 'pending', duration: null, tokens: null, startedAt: null, input: null, output: null },
  { id: 's8', name: 'Commit & Summary', status: 'pending', duration: null, tokens: null, startedAt: null, input: null, output: null },
];

// Creative Mode Run Detail Steps
export const CREATIVE_RUN_STEPS = [
  {
    id: 'c1', name: 'Script Generation', status: 'success',
    duration: '4.2s', tokens: 8200, cost: 0.04, startedAt: '14:10:00',
    connector: 'Claude', connectorType: 'llm',
    input: 'Brief: Q2 Brand Launch video, 60s, tone: confident & modern, audience: B2B SaaS buyers',
    output: '6-scene script generated:\nScene 1: Opening — brand statement (0:00–0:08)\nScene 2: Problem — market noise (0:08–0:18)\nScene 3: Solution — product intro (0:18–0:32)\nScene 4: Demo — key features (0:32–0:46)\nScene 5: Social proof (0:46–0:54)\nScene 6: CTA (0:54–1:00)',
  },
  {
    id: 'c2', name: 'Style Reference', status: 'success',
    duration: '6.8s', tokens: 6100, cost: 0.18, startedAt: '14:10:05',
    connector: 'Gemini', connectorType: 'llm',
    input: 'Reference images: 3 uploaded · Style: dark tech, high contrast, sharp typography',
    output: 'Style prompt synthesized:\n"Dark background #0a0a0f, electric blue accents #4d8eff, sans-serif bold typography, cinematic depth-of-field, professional product photography aesthetic, high contrast lighting"',
  },
  {
    id: 'c3', name: 'Scene Image Generation', status: 'waiting_review',
    duration: '14m 20s', tokens: 4800, cost: 2.40, startedAt: '14:10:12',
    connector: 'Gemini', connectorType: 'image_gen',
    input: '6 scenes × style prompt → generate hero images',
    output: '8 images generated across 6 scenes\n3 pending human review',
    assets: [
      {
        sceneId: 'scene-1', sceneName: 'Opening — Brand Statement',
        aspectRatio: '16:9',
        versions: [
          { v: 1, status: 'rejected', connector: 'Gemini', cost: 0.04, feedback: '構圖太散，品牌 logo 不夠突出', color: '#1a2a4a' },
          { v: 2, status: 'rejected', connector: 'Gemini', cost: 0.04, feedback: '背景太亮，失去科技感', color: '#2a1a3a' },
          { v: 3, status: 'approved', connector: 'Gemini', cost: 0.04, feedback: null, color: '#0d1829' },
        ],
      },
      {
        sceneId: 'scene-2', sceneName: 'Problem — Market Noise',
        aspectRatio: '16:9',
        versions: [
          { v: 1, status: 'rejected', connector: 'Gemini', cost: 0.04, feedback: '概念不清楚，太抽象', color: '#2a2a1a' },
          { v: 2, status: 'pending', connector: 'Gemini', cost: 0.04, feedback: null, color: '#1a1a2a' },
        ],
      },
      {
        sceneId: 'scene-3', sceneName: 'Solution — Product Intro',
        aspectRatio: '16:9',
        versions: [
          { v: 1, status: 'pending', connector: 'Gemini', cost: 0.04, feedback: null, color: '#0a1a2a' },
        ],
      },
      {
        sceneId: 'scene-4', sceneName: 'Demo — Key Features',
        aspectRatio: '16:9',
        versions: [
          { v: 1, status: 'generating', connector: 'Gemini', cost: null, feedback: null, color: '#1a0a1a' },
        ],
      },
    ],
  },
  {
    id: 'c4', name: 'Motion Generation', status: 'pending',
    duration: null, tokens: null, cost: null, startedAt: null,
    connector: 'Runway', connectorType: 'video_gen',
    input: null, output: null, assets: [],
  },
  {
    id: 'c5', name: 'Assembly & Compositing', status: 'pending',
    duration: null, tokens: null, cost: null, startedAt: null,
    connector: 'Internal', connectorType: 'processor',
    input: null, output: null, assets: [],
  },
  {
    id: 'c6', name: 'Final Review', status: 'pending',
    duration: null, tokens: null, cost: null, startedAt: null,
    connector: null, connectorType: null,
    input: null, output: null, assets: [],
  },
];

export const CONNECTORS = [
  {
    id: 'gemini-main',
    name: 'Gemini',
    provider: 'Google',
    type: 'llm',
    capabilities: ['text_generation', 'image_generation', 'image_understanding'],
    model: 'gemini-2.5-pro',
    status: 'connected',
    latencyAvg: '1.2s',
    quotaUsed: 892,
    quotaMax: 1500,
    lastCheck: '2 min ago',
    endpoint: 'https://generativelanguage.googleapis.com/v1beta',
  },
  {
    id: 'claude-main',
    name: 'Claude',
    provider: 'Anthropic',
    type: 'llm',
    capabilities: ['text_generation', 'code_generation'],
    model: 'claude-sonnet-4-5',
    status: 'connected',
    latencyAvg: '0.8s',
    quotaUsed: 341,
    quotaMax: null,
    lastCheck: '2 min ago',
    endpoint: 'https://api.anthropic.com/v1',
  },
  {
    id: 'runway-main',
    name: 'Runway',
    provider: 'RunwayML',
    type: 'video_gen',
    capabilities: ['video_generation', 'image_to_video'],
    model: 'gen-4-turbo',
    status: 'rate_limited',
    latencyAvg: '45s',
    quotaUsed: 50,
    quotaMax: 50,
    resetIn: '14 min',
    lastCheck: '1 min ago',
    endpoint: 'https://api.runwayml.com/v1',
  },
  {
    id: 'midjourney-main',
    name: 'Midjourney',
    provider: 'Midjourney',
    type: 'image_gen',
    capabilities: ['image_generation'],
    model: 'v7',
    status: 'disconnected',
    latencyAvg: null,
    quotaUsed: 0,
    quotaMax: 200,
    error: 'API key expired',
    lastCheck: '5 min ago',
    endpoint: 'https://api.midjourney.com/v1',
  },
];

export const ROLES = [
  {
    id: 'backend-engineer', name: 'Backend Engineer', mode: 'code',
    description: 'API endpoints, database migrations, background jobs',
    promptLayers: {
      global: `You are a senior backend engineer working on a production codebase. Implement the requested feature with minimal changes.\n\nRules:\n- Write idiomatic code matching existing style\n- Always handle errors explicitly\n- Add tests for new functionality\n- Do not refactor unrelated code`,
      project: `Project: {project_name}\nStack: {stack}\nTest command: {test_cmd}\n\nSchema:\n{schema_context}\n\nExisting patterns:\n{code_patterns}`,
      task: `Task: {task_description}\n\nFiles to modify:\n{target_files}\n\nCurrent failures:\n{test_failures}`,
    },
  },
  {
    id: 'security-engineer', name: 'Security Engineer', mode: 'code',
    description: 'Auth flows, token handling, security hardening',
    promptLayers: {
      global: `You are a security-focused engineer. Every change must consider security implications.\n\nRules:\n- Never log sensitive data\n- Validate all inputs at boundary\n- Use constant-time comparison for secrets\n- Follow OWASP guidelines`,
      project: `Project: {project_name}\nStack: {stack}\nSecurity policy: {security_policy}`,
      task: `Task: {task_description}\nTest failures: {test_failures}`,
    },
  },
  {
    id: 'data-engineer', name: 'Data Engineer', mode: 'code',
    description: 'Pipeline processing, feature engineering, model integration',
    promptLayers: {
      global: `You are a data engineer working on ML infrastructure.\n\nRules:\n- Ensure idempotency in pipeline steps\n- Handle schema evolution gracefully\n- Log data quality metrics`,
      project: `Project: {project_name}\nStack: {stack}\nPipeline config: {pipeline_config}`,
      task: `Task: {task_description}\nTest failures: {test_failures}`,
    },
  },
  {
    id: 'creative-director', name: 'Creative Director', mode: 'creative',
    description: 'Video scripting, visual direction, asset generation orchestration',
    promptLayers: {
      global: `You are a creative director for AI-generated video content. Your job is to produce high-quality, on-brand visual assets.\n\nRules:\n- Maintain visual consistency across all scenes\n- Consider pacing and narrative flow\n- Generate multiple variations for human review\n- Preserve the style reference throughout`,
      project: `Project: {project_name}\nBrand: {brand_guidelines}\nStyle reference: {style_prompt}\nAspect ratio: {aspect_ratio}`,
      task: `Scene: {scene_description}\nNarrative context: {narrative_context}\nPrevious feedback: {review_feedback}`,
    },
  },
];

export const INSIGHTS = {
  todaySummary: {
    codeRuns: 7, codeSuccess: 5, codeFailed: 2,
    creativeRuns: 3, creativeApproved: 2, creativePending: 1,
    tokensTotal: 320400, estimatedCost: 14.80,
    needsReview: 1, needsIntervention: 1,
  },
  firstPassRate: [
    { date: 'Apr 17', code: 48, creative: 55 },
    { date: 'Apr 18', code: 52, creative: 60 },
    { date: 'Apr 19', code: 45, creative: 50 },
    { date: 'Apr 20', code: 61, creative: 70 },
    { date: 'Apr 21', code: 58, creative: 65 },
    { date: 'Apr 22', code: 67, creative: 72 },
    { date: 'Apr 23', code: 71, creative: 68 },
    { date: 'Apr 24', code: 74, creative: 75 },
  ],
  avgFixAttempts: [2.8, 2.6, 3.1, 2.2, 2.4, 2.0, 1.8, 1.6],
  tokensByProject: [
    { project: 'commerce-api', tokens: 184000, cost: 0.92, mode: 'code' },
    { project: 'auth-service', tokens: 248000, cost: 1.24, mode: 'code' },
    { project: 'brand-video-q2', tokens: 92000, cost: 7.40, mode: 'creative' },
    { project: 'ml-pipeline', tokens: 141700, cost: 0.71, mode: 'code' },
    { project: 'product-demo-video', tokens: 56000, cost: 5.20, mode: 'creative' },
  ],
};

